version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18000:8000"
    depends_on:
      - db
      - postgres
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=app_user
      - DB_PASSWORD=app_password
      - DB_NAME=app_db
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=app_user
      - PG_PASSWORD=app_password
      - PG_DB=app_db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pgsql-init.sql:/docker-entrypoint-initdb.d/pgsql-init.sql

volumes:
  mysql_data:
  postgres_data:
