---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS MySQL 8.0 Database with managed password'

Parameters:
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group ID for the RDS instance
  
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs where the RDS instance will be deployed

Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: mysql-database
      DBName: my_database
      Engine: mysql
      EngineVersion: '8.0.33'
      AutoMinorVersionUpgrade: false
      DBInstanceClass: db.t4g.medium
      AllocatedStorage: 20
      StorageType: gp3
      StorageEncrypted: true
      BackupRetentionPeriod: 1
      MultiAZ: false
      DBSubnetGroupName: !Ref RDSSubnetGroup
      PubliclyAccessible: false
      VpcSecurityGroupIds:
        - !Ref SecurityGroupId
      MasterUsername: root
      ManageMasterUserPassword: true
      DeletionProtection: false

  # Subnet Group for RDS
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS MySQL database
      SubnetIds: !Ref SubnetIds
      Tags:
        - Key: Name
          Value: !Sub 'mysql-database-subnet-group'

Outputs:
  DBEndpoint:
    Description: RDS Instance Endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-DBEndpoint'

  MasterUserSecretArn:
    Description: ARN of the master user secret in Secrets Manager
    Value: !GetAtt RDSInstance.MasterUserSecret.SecretArn
    Export:
      Name: !Sub '${AWS::StackName}-MasterUserSecretArn'
